#true - on || false - off
Hide_NameTags: true
#Enable/Disable hiding nicknames
Show_NameTags: true
#Show player NameTag on right click
NameTags_show: '&l&6-=[&9<player>&l&6]=-'
#<player> - player nickname
Permissons: true
# | HideNicknames.switching | Allows you to enable or disable the visibility of names for all (Enable or disable plugin) (Default "Op")
NoPermissionsMessage: '&cYou do not have permission to use this command!'
#Permission message

Enabled_Worlds:
  - world
  - world_nether
  - world_the_end

# List of worlds where enabled plugin.