name: HideNickNames
version: V2.1
main: hidenicknames.hidenicknames.HideNickNames
api-version: 1.13
authors: [HolyGolf]
description: This plugin allows you to hide and show player nicknames.
website: https://github.com/HolyGolf
permissions:
  HideNicknames.switching:
    description: Allows you to enable or disable the visibility of names for all (Enable or disable plugin) and allows you to enable or disable the visibility of names for individual players.
commands:
  HNames:
    description: Plugin help
    usage: /<command>