name: HideNicknames
version: 1.6
main: hidenicknames.hidenicknames.HideNicknames
api-version: 1.13
authors: [HolyGolf]
description:  Hides player nicknames
permissions:
  HideNicknames.switching:
    description: Allows you to enable or disable the visibility of names for all (Enable or disable plugin) and allows you to enable or disable the visibility of names for individual players.
commands:
  HNames:
    description: Plugin help
    usage: /<command>
