#True - on, False - off
Hide_NameTags: true #Turning nickname hiding on and off on join
Show_NameTags: true #SHow player NameTag on right click
Permissons: false
# | HideNicknames.switching | Allows you to enable or disable the visibility of names for all (Enable or disable plugin) (Default "Op")
NoPermissionsMessage: You do not have permission to use this command!